### ISSUE TITLE
performance comparison

### ISSUE THREAD

**Issue by ant-mi5667** [SuperNG6/MSI-B660-Monterey-EFI#10]
@SuperNG6 thanks for this great efi. i was wondering that is 12700 cpu performance in hackintosh equivalent to m1 max?

**Comment by SuperNG6** [comment]
https://www.cpu-monkey.com/en/compare_cpu-intel_core_i7_12700-vs-apple_m1_max_24_gpu

This is a related test, you can compare the performance of each project.
