### ISSUE TITLE
新平台的几个问题想要了解

### ISSUE THREAD

**Issue by lclancey** [SuperNG6/MSI-B660-Monterey-EFI#3]
## 机型配置信息
None

## 请描述你的建议
1. 因为有VMware Fusion的重度需求，我B360的时候都是开启vt-d和vt-x的，请问这个硬件平台是否必须关闭虚拟化？
2. 5500xt是否仍需要`agdpmod=pikera`参数？是否需要修改其他内容？
3. 能提供一下网卡购买链接么，我以前买过几次网卡（m.2转接的`BCM94360CS2`，pcie转接的`94360CD`，笔记本的`BCM94352Z`网卡）没一个驱动成功的，都吃灰好几年了，很蛋疼

**Comment by SuperNG6** [comment]
1、OC配置文件里已经禁用vt-d了
2、至于是否可以是开启vt-d和vt-x的，可以自行尝试
3、5500t还是需要agdpmod=pikera
4、我买的是所谓的白苹果拆机网卡BCM94360CS2，我看愿景论坛很多都在用Fenvi T919网卡，应该还可以

**Comment by lclancey** [comment]
补充一下 还是B360平台 买了T919用了快半年了非常稳定
